version: "3.8"

services:
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus/
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - redis

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_SECURITY_ADMIN_USER=admin
    depends_on:
      - prometheus
  api:
    image: eip/api:latest
    container_name: api
    ports:
      - "8888:8888"
    depends_on:
      - redis
  front:
    image: eip/front:latest
    container_name: front
    ports:
      - "8880:8880"
    depends_on:
      - redis
      - api
  geo:
    image: eip/geo:latest
    container_name: geo
    ports:
      - "8080:8080"
    depends_on:
      - api

  # tempo:
  #   image: grafana/tempo:latest
  #   ports:
  #     - "14268:14268" # Port pour les traces
  #     - "14250:14250" # Port gRPC
  #   environment:
  #     - TEMPO_SERVER_HTTP_LISTENPORT=14268

  # tempo-query:
  #   image: grafana/tempo-query:latest
  #   ports:
  #     - "16686:16686"
  #   environment:
  #     - QUERY_FRONTEND_SERVER_ADDRESS=tempo:3100
  #   depends_on:
  #     - tempo

volumes:
  redis-data:
