FROM alpine:3.12

RUN apk --no-cache add ca-certificates \
    && apk add tzdata \
    && ln -s /usr/share/zoneinfo/Europe/Paris /etc/localtime
WORKDIR /root/
COPY ./app ./app
COPY ./public ./public
COPY ./templates ./templates
CMD ["./app"]